### PR TITLE
Fix metrics for new HTML Format of Facebook

### PR DESCRIPTION
**Pull request by claudiofullscreen**
Closes #66

### CODE REVIEW

**Comment by claudiofullscreen** [comment]
@himberjack I have taken the changes you suggested in #66 but added as a new condition.

The reason is that Facebook makes changes in their HTML progressively, so the old HTML might still be returned for some videos. With this PR, both old and new style should work correctly and tests should pass.

**Comment by himberjack** [comment]
perfect! Thanks



 Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=oded@shafranet.com&idSignature=22>

On Thu, Jan 19, 2017 at 9:16 PM, claudiofullscreen <notifications@github.com

**Comment by claudiofullscreen** [comment]
@himberjack I just noticed you added a new commit to #66 which tackles a different situation (404). I'll try to include that in a separate commit/PR as well. I didn't notice that extra commit before.

**Comment by himberjack** [comment]
yes I did it right after. Please include this in the next release as its
alerts for false positive....



 Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=oded@shafranet.com&idSignature=22>

On Thu, Jan 19, 2017 at 9:17 PM, claudiofullscreen <notifications@github.com

**Comment by claudiofullscreen** [comment]
Closes #68

**Pull request closed without merging**
