### PR TITLE
set locale field as en_US

### PR DESCRIPTION
**Pull request by claudiofullscreen**
Closes #56

### CODE REVIEW

**Comment by claudiofullscreen** [comment]
I tried changing the setting to "Build only if .travis.yml" present

screen shot 2016-08-05 at 9 58 05 am

**Comment by claudiofullscreen** [comment]
@kangkyu @philipqnguyen looks like it worked.

I think we need to bump the patch version, update the changelog and release!

**Comment by claudiofullscreen** [comment]
And in the CHANGELOG explain why we need this change.

**Comment by philipqnguyen** [comment]
😃

**Comment by philipqnguyen** [comment]
I'll merge this and bump version && changelog in another commit/pr.

**Pull request merged**
